name: test

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.command }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        command:
          - nimble build
          - nimble check
          - nimble format && git diff --exit-code
          - nimble lint
          - nimble test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: jiro4989/setup-nim-action@3a60cf06f20c1cf3a9becf76b30288c0361d5f1e # v2.2.2
        with:
          nim-version: 2.2.4
          nim-install-directory: nim
          parent-nim-install-directory: /opt
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: ${{ matrix.command }}
      - if: matrix.command == 'nimble build'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: dede
          path: ./bin/dede
  release:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    permissions:
      contents: read
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - if: matrix.os != 'macos-latest'
        uses: jiro4989/setup-nim-action@3a60cf06f20c1cf3a9becf76b30288c0361d5f1e # v2.2.2
        with:
          nim-version: stable
          nim-install-directory: nim
          parent-nim-install-directory: /opt
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - if: matrix.os == 'macos-latest'
        run: brew update && brew install nim
      - run: nimble release
      - if: matrix.os == 'windows-latest'
        uses: actions/download-artifact@v4
        with:
          name: dede-${{ matrix.os }}
          path: ./bin/dede.exe
      - if: matrix.os != 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: dede-${{ matrix.os }}
          path: ./bin/dede
